deepnotes:
  database_uri: "sqlite:///notes.db"
  max_iterations: 5
  output_formats: [ "json", "markdown" ]
  data_sources:
    - source_type: "database"
      query: "SELECT FROM research_data"
      connection_params:
        uri: "postgresql://${DB_USER}:${DB_PASS}@localhost/research"

llm:
  provider: "openai"
  model: "gpt-4o"
  base_url: "https://api.example.com/v1"
  api_key: "${LLM_API_KEY}"